
on:
   
  push:
    branches:
      - main
  
      # note that your "main" branch might be called main instead of master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v4
      with:
        url: https://full-stack-open-pokedex-update.onrender.com/health
