name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
    simple_deployment_pipeline:
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: '20'
        - name: Install dependencies
          run: npm install
        - name: Check style
          run: npm run eslint
        - name: build
          run: npm run build
        - name: test
          run: npm run test
        - name: e2e tests
          id: test
          uses: cypress-io/github-action@v5
          with:
            command: npm run test:e2e
            start: npm run start-prod
            wait-on: http://localhost:5000
        - name: Trigger deployment
          if: ${{ github.event_name == 'push' }}
          run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
        - name: Test Failure
          uses: rjstone/discord-webhook-notify@v1
          if: ${{ failure() && steps.test.conclusion == 'failure' }}
          with:
            severity: error
            details: e2e testing has failed 
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    
    tag_release:
        needs: [simple_deployment_pipeline]
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v4
        - name: TEST GITHUB CONEXT
          run: echo "$COMMIT_MESSAGES"
        - name: Bump version and push tag
          uses: anothrNick/github-tag-action@1.69.0
          env:
            COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DEFAULT_BUMP: patch
          if: ${{ github.event_name == 'push' && !contains(env.COMMIT_MESSAGES, 'skip')}}
        - name: Test Success
          uses: rjstone/discord-webhook-notify@v1
          if: success()
          with:
            severity: info
            details: Test Succeeded!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        - name: Test Failure
          uses: rjstone/discord-webhook-notify@v1
          if: failure()
          with:
            severity: error
            details: Test Failed! 
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}